USE [LOS-2020-2-20-10-38]
GO

/****** Object:  Table [dbo].[TBL_KANTOR]    Script Date: 27/02/2020 16:47:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_KANTOR](
	[KD_KANTOR] [char](3) NOT NULL,
	[PARENT] [char](3) NULL,
	[LEVEL] [char](1) NULL,
	[NAME] [varchar](50) NULL,
	[STATUS] [char](1) NULL,
 CONSTRAINT [PK_TBL_KANTOR] PRIMARY KEY CLUSTERED 
(
	[KD_KANTOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


