USE [LOS-2020-2-20-10-38]
GO

/****** Object:  Table [dbo].[TBL_REFERENSI]    Script Date: 27/02/2020 08:52:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_REFERENSI](
	[REFERENSI_ID] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_ID] [varchar](50) NULL,
	[REF] [varchar](50) NULL,
	[DESC] [varchar](300) NULL,
	[GROUP_ID2] [varchar](50) NULL,
	[REF2] [varchar](50) NULL,
	[DESC2] [varchar](300) NULL,
 CONSTRAINT [TBL_REFERENSI_PK] PRIMARY KEY CLUSTERED 
(
	[REFERENSI_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


